project:
  type: website

execute:
  freeze: auto

website:
  title: "Ketchbrook Analytics Blog"
  favicon: "www/favicon.ico"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ketchbrookanalytics
      - icon: linkedin
        href: https://www.linkedin.com/company/ketchbrook-analytics
format:
  html:
    theme: lux
    css: styles.css
    code-fold: true
    highlight-style: breeze
    code-link: true
    toc: true
    toc-depth: 2
